'''
LOL FOR FUN
'''
def GET_COLOR_BASH(a,b):
	return "\033["+str(a)+";"+str(b)+"m"

COLORSBASH = {
"RED":GET_COLOR_BASH(0,31),
"GREEN":GET_COLOR_BASH(1,32),
"PURPLE":GET_COLOR_BASH(0,35),
"BLACK":GET_COLOR_BASH(0,30),
"BROWN":GET_COLOR_BASH(0,33),
"PURPLE":GET_COLOR_BASH(0,35),
"CYAN":GET_COLOR_BASH(0,36),
"YELLOW":GET_COLOR_BASH(1,33),
"WHITE":GET_COLOR_BASH(1,37),
"END":"\033[0m"
}
